# Generated by Django 4.2.4 on 2023-08-09 08:11

import commerce.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('hashed_password', models.CharField(max_length=5000)),
                ('country', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('original_price', models.FloatField(default=0.0)),
                ('price_percentage_cut', models.IntegerField(default=0, validators=[commerce.validators.validate_percentage_cut])),
                ('amount_available_in_stock', models.IntegerField(default=0)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
