# Generated by Django 4.2.4 on 2023-08-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_customer_hashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
