# Generated by Django 4.2.4 on 2023-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_alter_customer_hashed_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
