# Generated by Django 4.2.4 on 2023-08-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_product_product_image_url_product_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_url',
            field=models.FileField(max_length=10000, null=True, upload_to=''),
        ),
    ]
